  
trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: CmdLine@2
  inputs:
    script: 'docker run -p 8090:8090 -d -i --name ZAPTESTS owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0'
  displayName: Running ZAP container

- task: Maven@3
  inputs:
  
    mavenPomFile: './smartHub-bdd/pom.xml'
    goals: 'clean verify -PdontUseTheForks'
    options: '-Dcucumber.filter.tags="@sanity" -DappConfig="AppConfigDEV.properties" -Dcucumber.features="src/test/resources/features"'
    publishJUnitResults: true
    testResultsFiles: './smartHub-bdd/target/site/serenity/'
    testRunTitle: 'Help'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- bash: |
    sudo chmod o+x ./smartHub-bdd/target/site/serenity

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.Repository.LocalPath)/smartHub-bdd/target'
#   ArtifactName: 'Full report'
#    publishLocation: 'Container'
#  displayName: Publish the report folder

- task: CmdLine@2
  inputs:
    script: 'docker exec ZAPTESTS zap-cli -p 8090 status -t 120'
  displayName: Checking zap status inside the container