  
trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: CmdLine@2
  inputs:
    script: 'docker run -p 8090:8090 -d -i owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0'
- task: CmdLine@2
  inputs:
    script: 'cd /home/vsts/work/1/s/ssmartHub-bdd/ && mvn clean verify -DappConfig="AppConfigQA.properties" -Dserenity.proxy.http="127.0.0.1" -Dserenity.proxy.http_port="7777" -Dcucumber.filter.tags="@debug" -Dcucumber.features="src/test/resources/features"'