# The API will need to verify that each business rule could be created from a template
Feature: Save and display business rule template
  As a Business rule expert
  I want to create a business rule template
  So that each business rule could be created from a template

#  Background: User is persisted in DataBase and logged in portal
#    Given User is persisted in database:
#      | username | name     |
#      | password | password |
#    And session token is generated for user

  @DISE-410
  Scenario: I create new business rule template with type Routing
    Given I send post request to create new business rule template with fields:
      | name           | {STRING:10}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | description    | AAAAAA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | ruleXml        | "{\"Elements\":[{\"Type\":0,\"Name\":\"_divRuleEditor0\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"if\"},{\"Type\":1,\"Name\":\"_divRuleEditor1\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":3,\"Name\":\"_divRuleEditor2\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"equal\"},{\"Type\":4,\"Name\":\"_divRuleEditor4\",\"Oper\":0,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"123\"},{\"Type\":6,\"Name\":\"_divRuleEditor5\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"then\"},{\"Type\":17,\"Name\":\"_divRuleEditor6\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"set\"},{\"Type\":1,\"Name\":\"_divRuleEditor7\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":17,\"Name\":\"_divRuleEditor8\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"to\"},{\"Type\":4,\"Name\":\"_divRuleEditor10\",\"Oper\":0,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"123\"}],\"IsLoadedRuleOfEvalType\":false,\"Command\":\"ceExtract\",\"Mode\":0,\"Name\":\"A123\",\"SkipNameValidation\":false}" |
      | type           | Routing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
    Then the status code should be '200'
    And business rule template is persisted in database

  @DISE-410
  Scenario: I create new business rule template with type Validation
    Given I send post request to create new business rule template with fields:
      | name           | {STRING:11}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | description    | {EMPTY}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | ruleXml        | "{\"Elements\":[{\"Type\":0,\"Name\":\"_divRuleEditor0\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"if\"},{\"Type\":1,\"Name\":\"_divRuleEditor1\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":3,\"Name\":\"_divRuleEditor2\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"equal\"},{\"Type\":4,\"Name\":\"_divRuleEditor4\",\"Oper\":0,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"123\"},{\"Type\":6,\"Name\":\"_divRuleEditor5\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"then\"},{\"Type\":17,\"Name\":\"_divRuleEditor6\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"set\"},{\"Type\":1,\"Name\":\"_divRuleEditor7\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":17,\"Name\":\"_divRuleEditor8\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"to\"},{\"Type\":4,\"Name\":\"_divRuleEditor10\",\"Oper\":0,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"123\"}],\"IsLoadedRuleOfEvalType\":false,\"Command\":\"ceExtract\",\"Mode\":0,\"Name\":\"A123\",\"SkipNameValidation\":false}" |
      | type           | Validation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    Then the status code should be '200'
    And business rule template is persisted in database

  @DISE-410
  Scenario: I try to create new business rule template with empty value of RuleXml
    Given I send post request to create new business rule template with fields:
      | Name           | {STRING:12} |
      | Description    | {EMPTY}     |
      | RuleXml        | {EMPTY}     |
      | Type           | Routing     |
    Then the status code should be '400'


  @DISE-410
  Scenario: I try to create new business rule template with empty value of Name
    Given I send post request to create new business rule template with fields:
      | Name           | {EMPTY}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | Description    | {EMPTY}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | RuleXml        | "{\"Elements\":[{\"Type\":0,\"Name\":\"_divRuleEditor14\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"if\"},{\"Type\":1,\"Name\":\"_divRuleEditor15\",\"Oper\":1,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"Transaction.Amount\",\"IsRule\":false,\"Dec\":false,\"Cal\":true,\"Min\":-2147483648,\"Max\":2147483647},{\"Type\":3,\"Name\":\"_divRuleEditor16\",\"Oper\":1,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"equal\"},{\"Type\":4,\"Name\":\"_divRuleEditor18\",\"Oper\":1,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"151\"},{\"Type\":6,\"Name\":\"_divRuleEditor19\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"then\"},{\"Type\":17,\"Name\":\"_divRuleEditor20\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"set\"},{\"Type\":1,\"Name\":\"_divRuleEditor21\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":17,\"Name\":\"_divRuleEditor22\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"to\"},{\"Type\":4,\"Name\":\"_divRuleEditor24\",\"Oper\":0,\"FuncType\":4,\"InpType\":0,\"CalType\":9,\"Value\":\"Transaction.Card.Country\"},{\"Type\":6,\"Name\":\"_divRuleEditor25\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"and\"},{\"Type\":17,\"Name\":\"_divRuleEditor26\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"set\"},{\"Type\":1,\"Name\":\"_divRuleEditor27\",\"Oper\":4,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.Interrupt\",\"IsRule\":false},{\"Type\":17,\"Name\":\"_divRuleEditor28\",\"Oper\":4,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"to\"},{\"Type\":4,\"Name\":\"_divRuleEditor29\",\"Oper\":4,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"true\"}],\"IsLoadedRuleOfEvalType\":false,\"Command\":\"ceExtract\",\"Mode\":0,\"Name\":\"AABBCC\",\"SkipNameValidation\":false}" |
      | Type           | Routing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    Then the status code should be '400'


  @DISE-410
  Scenario: I try to create new business rule template with existing name
    Given I send post request to create new business rule template with fields:
      | Name           | Name_Name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | Description    | {EMPTY}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | RuleXml        | "{\"Elements\":[{\"Type\":0,\"Name\":\"_divRuleEditor0\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"if\"},{\"Type\":1,\"Name\":\"_divRuleEditor1\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":3,\"Name\":\"_divRuleEditor2\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"equal\"},{\"Type\":4,\"Name\":\"_divRuleEditor4\",\"Oper\":0,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"123\"},{\"Type\":6,\"Name\":\"_divRuleEditor5\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"then\"},{\"Type\":17,\"Name\":\"_divRuleEditor6\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"set\"},{\"Type\":1,\"Name\":\"_divRuleEditor7\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":17,\"Name\":\"_divRuleEditor8\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"to\"},{\"Type\":4,\"Name\":\"_divRuleEditor10\",\"Oper\":0,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"123\"}],\"IsLoadedRuleOfEvalType\":false,\"Command\":\"ceExtract\",\"Mode\":0,\"Name\":\"A123\",\"SkipNameValidation\":false}" |
      | Type           | Validation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    And I send post request to create new business rule template with fields:
      | RuleTemplateId | {EMPTY}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | Name           | Name_Name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | Description    | {EMPTY}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | RuleXml        | "{\"Elements\":[{\"Type\":0,\"Name\":\"_divRuleEditor0\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"if\"},{\"Type\":1,\"Name\":\"_divRuleEditor1\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":3,\"Name\":\"_divRuleEditor2\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"equal\"},{\"Type\":4,\"Name\":\"_divRuleEditor4\",\"Oper\":0,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"123\"},{\"Type\":6,\"Name\":\"_divRuleEditor5\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"then\"},{\"Type\":17,\"Name\":\"_divRuleEditor6\",\"Oper\":16,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"set\"},{\"Type\":1,\"Name\":\"_divRuleEditor7\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"ExecutionResult.RoutingResult.SelectedMID\",\"IsRule\":false,\"Max\":256},{\"Type\":17,\"Name\":\"_divRuleEditor8\",\"Oper\":0,\"FuncType\":4,\"InpType\":2,\"CalType\":9,\"Value\":\"to\"},{\"Type\":4,\"Name\":\"_divRuleEditor10\",\"Oper\":0,\"FuncType\":4,\"InpType\":1,\"CalType\":9,\"Value\":\"123\"}],\"IsLoadedRuleOfEvalType\":false,\"Command\":\"ceExtract\",\"Mode\":0,\"Name\":\"A123\",\"SkipNameValidation\":false}" |
      | Type           | Validation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    Then the status code should be '400'
